name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Se met Ã  jour chaque nuit
  workflow_dispatch: # Permet de le lancer manuellement
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: EstevanCerq
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
